spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: admin
    password: admin
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
